# Generated by Django 3.2.16 on 2023-05-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='test',
        ),
    ]
